CREATE USER 'debezium'@'%' IDENTIFIED BY 'dbz';
GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT  ON *.* TO 'debezium'@'%';

CREATE DATABASE demo;
USE demo;

CREATE TABLE users (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  platform VARCHAR(255),
  country VARCHAR(3),
  ip_address VARCHAR(30),
  nb_orders INT DEFAULT 0 NOT NULL
);

INSERT INTO users
VALUES (DEFAULT, "Alice", "Windows", "PL", "10.10.10.10", 0),
       (DEFAULT, "Bob", "Android", "FR", "14.14.14.14", 1);
